# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [123]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [126]:
newdf = pd.read_csv("../output_data/cities.csv")
newdf

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,ribeira grande,42.7461,-8.4439,17.25,94,75,1.54,ES,1627273915
1,mataura,-46.1927,168.8643,9.71,95,100,0.82,NZ,1627273916
2,soto la marina,-32.8107,-61.4026,10.62,69,0,3.98,AR,1627273916
3,san juan,13.3034,-4.8956,25.99,74,26,4.01,ML,1627273916
4,nyurba,63.2842,118.3319,31.67,29,2,3.37,RU,1627273917
...,...,...,...,...,...,...,...,...,...
578,tharad,24.3961,71.6267,27.99,84,100,7.48,IN,1627274180
579,wajir,1.7471,40.0573,22.44,64,7,8.41,KE,1627274181
580,sioux lookout,42.7333,-96.2336,24.47,88,40,1.54,US,1627274181
581,lata,40.1629,-8.3327,16.86,97,85,1.04,PT,1627274181
582,sainte-adele,45.9501,-74.1325,20.90,96,75,2.08,CA,1627274182

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [127]:
# Store latitude and longitude in locations
locations = newdf[["Lat", "Lng"]]

# # Fill NaN values and convert to float
NewHumidity = newdf["Humidity"]

In [128]:
# Plot Heatmap
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)


# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=NewHumidity, 
                                 dissipating=False,  max_intensity = NewHumidity.max(),
                                 point_radius=3)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [129]:
Criteriadf = newdf.loc[(newdf["Wind Speed"] <= 10) & (newdf["Cloudiness"]== 0)]
Criteriadf

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
2,soto la marina,-32.8107,-61.4026,10.62,69,0,3.98,AR,1627273916
12,albany,42.6001,-73.9662,20.71,95,0,1.65,US,1627273921
13,petropavlovsk-kamchatskiy,53.0452,158.6483,25.33,57,0,4.00,RU,1627273869
14,novyy urengoy,45.0072,38.9819,25.62,66,0,5.00,RU,1627273922
29,coihaique,-45.5752,-72.0662,3.97,60,0,4.12,CL,1627273927
43,abnub,27.2696,31.1511,25.12,54,0,3.26,EG,1627273932
47,adrar,20.5022,-10.0711,28.94,35,0,4.47,MR,1627273933
56,puerto escondido,36.5939,-6.2330,21.81,84,0,3.09,ES,1627273936
64,zhezkazgan,47.8043,67.7144,27.08,26,0,8.25,KZ,1627273944
71,puerto ayora,36.5939,-6.2330,21.81,84,0,3.09,ES,1627273947
109,lixourion,38.2019,20.4314,21.92,59,0,1.65,GR,1627273963
120,arraial do cabo,-22.8362,-46.6460,12.67,47,0,2.48,BR,1627273967
165,mokhsogollokh,61.4681,128.9203,27.46,31,0,4.05,RU,1627273987
185,sovetskaya,44.7769,41.1722,24.07,59,0,7.45,RU,1627273995
202,florianopolis,-27.6146,-48.5012,18.68,89,0,0.45,BR,1627274009
216,korla,41.7597,86.1469,36.58,11,0,4.95,CN,1627274014
235,cherskiy,68.7500,161.3000,12.48,46,0,7.74,RU,1627273991
245,rio gallegos,38.3000,21.7833,27.00,42,0,3.04,GR,1627274025
283,itapolis,-21.5956,-48.8128,14.81,46,0,3.38,BR,1627274039
289,emba,48.8264,58.1442,25.98,34,0,3.38,KZ,1627274041
292,neuquen,-38.9516,-68.0591,4.94,93,0,2.57,AR,1627273776
301,coquimbo,-29.9533,-71.3436,9.85,93,0,2.57,CL,1627273800
308,jalu,29.0331,21.5482,23.88,52,0,3.35,LY,1627274050
316,namibe,-15.1961,12.1522,20.80,56,0,3.32,AO,1627273966
318,komsomolskiy,40.4272,71.7189,36.40,19,0,2.06,UZ,1627274059
328,parkent,41.2944,69.6764,32.90,10,0,3.71,UZ,1627274063
331,saint-pierre,-21.3393,55.4781,20.80,60,0,3.60,RE,1627274064
339,matveyevka,52.1500,56.1833,19.53,33,0,3.99,RU,1627274067
342,bardiyah,31.7561,25.0865,25.16,68,0,4.30,LY,1627274068
364,vallenar,-28.5708,-70.7581,10.75,59,0,1.05,CL,1627274076
374,melendugno,40.2747,18.3368,25.81,83,0,2.57,IT,1627274083
375,rawah,34.4816,41.9093,37.79,20,0,5.12,IQ,1627274083
395,gwanda,-20.9333,29.0000,4.60,89,0,2.12,ZW,1627274091
398,lulea,65.5842,22.1547,17.04,82,0,1.54,SE,1627274092
409,shetpe,44.1667,52.1167,30.36,20,0,6.84,KZ,1627274097
421,rundu,-17.9333,19.7667,5.98,67,0,2.84,NaN,1627274101
435,awjilah,29.1081,21.2869,23.81,54,0,3.48,LY,1627274114
441,bayji,34.9311,43.4870,39.42,17,0,5.44,IQ,1627274116
449,neyshabur,36.2133,58.7958,32.34,15,0,5.47,IR,1627274119
463,puerto penasco,36.5939,-6.2330,21.81,84,0,3.09,ES,1627273947
465,riyadh,24.6877,46.7219,35.03,17,0,2.06,SA,1627274019
481,suntar,62.1444,117.6319,31.37,30,0,2.48,RU,1627274132
489,copiapo,-27.3667,-70.3333,8.83,72,0,0.67,CL,1627273767
494,safaga,26.7292,33.9365,27.97,47,0,4.58,EG,1627274136
496,hun,29.1268,15.9477,23.40,57,0,2.90,LY,1627274137
504,mizdah,31.4451,12.9801,21.64,55,0,2.62,LY,1627274140
507,apollonia,36.9716,24.7231,23.28,69,0,8.87,GR,1627274141
524,nurota,40.5614,65.6886,37.05,15,0,9.84,UZ,1627274152
527,puerto colombia,36.5939,-6.2330,21.81,84,0,3.09,ES,1627273936
533,naantali,60.4674,22.0243,20.06,82,0,0.51,FI,1627274156
537,bestobe,52.4994,73.0975,21.14,49,0,7.24,KZ,1627274157
543,nalut,30.3333,10.8500,24.50,30,0,5.26,LY,1627274160
544,kars,40.6020,43.0950,20.47,82,0,1.03,TR,1627274160
554,aswan,24.0934,32.9070,26.61,34,0,5.14,EG,1627274164
573,hervey bay,33.4982,-93.7771,29.25,71,0,0.40,US,1627274175

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [132]:
hotel_df = Criteriadf
hotel_df['Hotel Name']=''
hotel_df.head()

<ipython-input-132-4a38c30ba3a3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df['Hotel Name']=''

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
2,soto la marina,-32.8107,-61.4026,10.62,69,0,3.98,AR,1627273916,
12,albany,42.6001,-73.9662,20.71,95,0,1.65,US,1627273921,
13,petropavlovsk-kamchatskiy,53.0452,158.6483,25.33,57,0,4.00,RU,1627273869,
14,novyy urengoy,45.0072,38.9819,25.62,66,0,5.00,RU,1627273922,
29,coihaique,-45.5752,-72.0662,3.97,60,0,4.12,CL,1627273927,

In [133]:
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
params = {'radius':5000, 'types': 'hotel', 'key': g_key}

In [136]:
for index, row in hotel_df.iterrows():
    Lat = row['Lat']
    Lng = row['Lng']
    params['location'] = f'{Lat},{Lng}'
    response = requests.get(base_url, params=params).json()
    results = response['results']
    try:
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
hotel_df.head()

C:\Users\Priya\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
2,soto la marina,-32.8107,-61.4026,10.62,69,0,3.98,AR,1627273916,CaÃ±ada de GÃ³mez
12,albany,42.6001,-73.9662,20.71,95,0,1.65,US,1627273921,Voorheesville
13,petropavlovsk-kamchatskiy,53.0452,158.6483,25.33,57,0,4.00,RU,1627273869,Petropavlovsk-Kamchatskiy
14,novyy urengoy,45.0072,38.9819,25.62,66,0,5.00,RU,1627273922,Krasnodar
29,coihaique,-45.5752,-72.0662,3.97,60,0,4.12,CL,1627273927,Coyhaique

In [137]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [138]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))